extends Node

class_name CardDetails

func getCardFaceMap(deck:String="default"):
	
	if deck == "default":
		return {
		"Ah": { "suit": "hearts", "frame": 0 },
		"2h": { "suit": "hearts", "frame": 1 },
		"3h": { "suit": "hearts", "frame": 2 },
		"4h": { "suit": "hearts", "frame": 3 },
		"5h": { "suit": "hearts", "frame": 4 },
		"6h": { "suit": "hearts", "frame": 5 },
		"7h": { "suit": "hearts", "frame": 6 },
		"8h": { "suit": "hearts", "frame": 7 },
		"9h": { "suit": "hearts", "frame": 8 },
		"10h": { "suit": "hearts", "frame": 9 },
		"Jh": { "suit": "hearts", "frame": 10 },
		"Qh": { "suit": "hearts", "frame": 11 },
		"Kh": { "suit": "hearts", "frame": 12 },
		"Ac": { "suit": "clubs", "frame": 0 },
		"2c": { "suit": "clubs", "frame": 1 },
		"3c": { "suit": "clubs", "frame": 2 },
		"4c": { "suit": "clubs", "frame": 3 },
		"5c": { "suit": "clubs", "frame": 4 },
		"6c": { "suit": "clubs", "frame": 5 },
		"7c": { "suit": "clubs", "frame": 6 },
		"8c": { "suit": "clubs", "frame": 7 },
		"9c": { "suit": "clubs", "frame": 8 },
		"10c": { "suit": "clubs", "frame": 9 },
		"Jc": { "suit": "clubs", "frame": 10 },
		"Qc": { "suit": "clubs", "frame": 11 },
		"Kc": { "suit": "clubs", "frame": 12 },
		"Ad": { "suit": "diamonds", "frame": 0 },
		"2d": { "suit": "diamonds", "frame": 1 },
		"3d": { "suit": "diamonds", "frame": 2 },
		"4d": { "suit": "diamonds", "frame": 3 },
		"5d": { "suit": "diamonds", "frame": 4 },
		"6d": { "suit": "diamonds", "frame": 5 },
		"7d": { "suit": "diamonds", "frame": 6 },
		"8d": { "suit": "diamonds", "frame": 7 },
		"9d": { "suit": "diamonds", "frame": 8 },
		"10d": { "suit": "diamonds", "frame": 9 },
		"Jd": { "suit": "diamonds", "frame": 10 },
		"Qd": { "suit": "diamonds", "frame": 11 },
		"Kd": { "suit": "diamonds", "frame": 12 },
		"As": { "suit": "spades", "frame": 0 },
		"2s": { "suit": "spades", "frame": 1 },
		"3s": { "suit": "spades", "frame": 2 },
		"4s": { "suit": "spades", "frame": 3 },
		"5s": { "suit": "spades", "frame": 4 },
		"6s": { "suit": "spades", "frame": 5 },
		"7s": { "suit": "spades", "frame": 6 },
		"8s": { "suit": "spades", "frame": 7 },
		"9s": { "suit": "spades", "frame": 8 },
		"10s": { "suit": "spades", "frame": 9 },
		"Js": { "suit": "spades", "frame": 10 },
		"Qs": { "suit": "spades", "frame": 11 },
		"Ks": { "suit": "spades", "frame": 12 }
	}
	elif deck == "ancient":
				return {
		"Ah": { "suit": "hearts", "frame": 0 },
		"2h": { "suit": "hearts", "frame": 1 },
		"3h": { "suit": "hearts", "frame": 2 },
		"4h": { "suit": "hearts", "frame": 3 },
		"5h": { "suit": "hearts", "frame": 4 },
		"6h": { "suit": "hearts", "frame": 5 },
		"7h": { "suit": "hearts", "frame": 6 },
		"8h": { "suit": "hearts", "frame": 7 },
		"9h": { "suit": "hearts", "frame": 8 },
		"10h": { "suit": "hearts", "frame": 9 },
		"Ac": { "suit": "clubs", "frame": 0 },
		"2c": { "suit": "clubs", "frame": 1 },
		"3c": { "suit": "clubs", "frame": 2 },
		"4c": { "suit": "clubs", "frame": 3 },
		"5c": { "suit": "clubs", "frame": 4 },
		"6c": { "suit": "clubs", "frame": 5 },
		"7c": { "suit": "clubs", "frame": 6 },
		"8c": { "suit": "clubs", "frame": 7 },
		"9c": { "suit": "clubs", "frame": 8 },
		"10c": { "suit": "clubs", "frame": 9 },
		"Ad": { "suit": "diamonds", "frame": 0 },
		"2d": { "suit": "diamonds", "frame": 1 },
		"3d": { "suit": "diamonds", "frame": 2 },
		"4d": { "suit": "diamonds", "frame": 3 },
		"5d": { "suit": "diamonds", "frame": 4 },
		"6d": { "suit": "diamonds", "frame": 5 },
		"7d": { "suit": "diamonds", "frame": 6 },
		"8d": { "suit": "diamonds", "frame": 7 },
		"9d": { "suit": "diamonds", "frame": 8 },
		"10d": { "suit": "diamonds", "frame": 9 },
		"As": { "suit": "spades", "frame": 0 },
		"2s": { "suit": "spades", "frame": 1 },
		"3s": { "suit": "spades", "frame": 2 },
		"4s": { "suit": "spades", "frame": 3 },
		"5s": { "suit": "spades", "frame": 4 },
		"6s": { "suit": "spades", "frame": 5 },
		"7s": { "suit": "spades", "frame": 6 },
		"8s": { "suit": "spades", "frame": 7 },
		"9s": { "suit": "spades", "frame": 8 },
		"10s": { "suit": "spades", "frame": 9 }
	}

